language: rust
dist: xenial
sudo: required

notifications:
    email:
        on_success: never
        on_failure: change

rust:
    - 1.28.0

cache: cargo

before_script: cd qemu-from

script:
- cargo test
